// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: fibonacci.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BorderValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *BorderValues) Reset() {
	*x = BorderValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fibonacci_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorderValues) ProtoMessage() {}

func (x *BorderValues) ProtoReflect() protoreflect.Message {
	mi := &file_fibonacci_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorderValues.ProtoReflect.Descriptor instead.
func (*BorderValues) Descriptor() ([]byte, []int) {
	return file_fibonacci_proto_rawDescGZIP(), []int{0}
}

func (x *BorderValues) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *BorderValues) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

type FibonacciSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FibonacciNums []uint64 `protobuf:"varint,1,rep,packed,name=fibonacci_nums,json=fibonacciNums,proto3" json:"fibonacci_nums,omitempty"`
}

func (x *FibonacciSlice) Reset() {
	*x = FibonacciSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fibonacci_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibonacciSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciSlice) ProtoMessage() {}

func (x *FibonacciSlice) ProtoReflect() protoreflect.Message {
	mi := &file_fibonacci_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciSlice.ProtoReflect.Descriptor instead.
func (*FibonacciSlice) Descriptor() ([]byte, []int) {
	return file_fibonacci_proto_rawDescGZIP(), []int{1}
}

func (x *FibonacciSlice) GetFibonacciNums() []uint64 {
	if x != nil {
		return x.FibonacciNums
	}
	return nil
}

var File_fibonacci_proto protoreflect.FileDescriptor

var file_fibonacci_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x32, 0x0a, 0x0c, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x0e, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63,
	0x63, 0x69, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x69, 0x62, 0x6f, 0x6e,
	0x61, 0x63, 0x63, 0x69, 0x5f, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x0d, 0x66, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x4e, 0x75, 0x6d, 0x73, 0x32, 0x42,
	0x0a, 0x09, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x12, 0x35, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x12, 0x0d, 0x2e, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a,
	0x0f, 0x2e, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_fibonacci_proto_rawDescOnce sync.Once
	file_fibonacci_proto_rawDescData = file_fibonacci_proto_rawDesc
)

func file_fibonacci_proto_rawDescGZIP() []byte {
	file_fibonacci_proto_rawDescOnce.Do(func() {
		file_fibonacci_proto_rawDescData = protoimpl.X.CompressGZIP(file_fibonacci_proto_rawDescData)
	})
	return file_fibonacci_proto_rawDescData
}

var file_fibonacci_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fibonacci_proto_goTypes = []interface{}{
	(*BorderValues)(nil),   // 0: BorderValues
	(*FibonacciSlice)(nil), // 1: FibonacciSlice
}
var file_fibonacci_proto_depIdxs = []int32{
	0, // 0: Fibonacci.GetFibonacciSlice:input_type -> BorderValues
	1, // 1: Fibonacci.GetFibonacciSlice:output_type -> FibonacciSlice
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fibonacci_proto_init() }
func file_fibonacci_proto_init() {
	if File_fibonacci_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fibonacci_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorderValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fibonacci_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibonacciSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fibonacci_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fibonacci_proto_goTypes,
		DependencyIndexes: file_fibonacci_proto_depIdxs,
		MessageInfos:      file_fibonacci_proto_msgTypes,
	}.Build()
	File_fibonacci_proto = out.File
	file_fibonacci_proto_rawDesc = nil
	file_fibonacci_proto_goTypes = nil
	file_fibonacci_proto_depIdxs = nil
}
